server:
  port: 9003
#  servlet:
#    context-path: /api
spring:
  application:
    name: api
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
